spring:
  application:
    name: P2pDomicilios

  datasource:
    url: jdbc:postgresql://localhost:5432/p2p_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: secret-key
